name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04", "macos-12"] # comonicon doesn't support windows
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          persist-credentials: false

      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: "1.6"

      # FIXME: we need to build our dependencies, but we don't want to build this project here because it gets built next. can we avoid the duplicate work?
      - name: Build dependencies
        uses: julia-actions/julia-buildpkg@v1

      - name: Build tarballs
        run: julia -t auto --project deps/build.jl tarball

      - name: Run tests
        uses: julia-actions/julia-runtest@v1
