name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04", "windows-2022", "macos-12"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          persist-credentials: false

      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: "1.6"

      - name: Build dependencies
        uses: julia-actions/julia-buildpkg@v1

      - name: Build tarballs
        run: julia -t auto --project deps/build.jl tarball

      - run: ls -l deps/
      - run: ls -l build/
      - run: ls -l build/JuliaFormatterCLI/
