name: build

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04", "macos-12"] # comonicon doesn't support windows
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          persist-credentials: false

      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: "1.6"

      - run: julia -e 'import Pkg; Pkg.add("CodecZlib"); Pkg.activate("."); Pkg.instantiate()'

      - name: Build app tarball
        run: julia -t auto --project deps/build.jl app tarball

      - run: ls -l

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: julia-format
          path: ./julia-format-*.tar.gz

      - name: Run tests
        uses: julia-actions/julia-runtest@v1

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./julia-format-*.tar.gz
