name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04", "macos-12"] # comonicon doesn't support windows
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          persist-credentials: false

      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: "1.6"

      - run: julia --project -e 'import Pkg; Pkg.instantiate()'

      - name: Build tarballs
        run: julia -t auto --project deps/build.jl tarball
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: julia-format-${{ matrix.os }}
          path: build/julia-format

      - name: Run tests
        uses: julia-actions/julia-runtest@v1
